Encoding:
  Enabled: false

LineLength:
  Max: 300

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

# arbitrarily extended because reasons
MethodLength:
  Max: 20

ClassLength:
  Max: 200

TrivialAccessors:
  ExactNameMatch: true
